language: java
dist: trusty
# skip installation step
install: true

services:
  - mysql
  - postgresql
  
before_script:
  - psql -c 'create database keeptime;' -U postgres

addons:
 sonarcloud:
  organization: "andryxxx-github"

script:
- mvn -f keepchronos/pom.xml clean verify -Pjacoco coveralls:report sonar:sonar
